packages:
  - packages/*
  - examples/*
  - e2e
  - e2e/fixtures/*
  - website

catalog:
  '@hono/mcp': ^0.2.0
  '@modelcontextprotocol/ext-apps': ^1.0.1
  '@modelcontextprotocol/sdk': ^1.23.0
  '@types/node': ^24
  '@types/react': 19.2.14
  '@types/react-dom': 19.2.3
  '@unocss/reset': ^66.6.0
  hono: ^4.11.9
  preact: ^10.28.3
  react: 19.2.4
  react-dom: 19.2.4
  solid-js: 1.9.11
  typescript: ^5.9.3
  unocss: ^66.6.0
  vite: 7.3.1
  vite-plugin-singlefile: ^2.3.0
  zod: ^4.3.6
