packages:
  - packages/*
  - examples/*
  - e2e
  - e2e/fixtures/*
  - website

catalog:
  '@hono/mcp': ^0.2.0
  '@modelcontextprotocol/sdk': ^1.22.0
  '@modelcontextprotocol/ext-apps': ^1.0.1
  '@types/node': ^24.10.1
  '@types/react': 19.2.7
  '@types/react-dom': 19.2.3
  '@unocss/reset': ^66.6.0
  hono: ^4.10.6
  magic-string: ^0.30.21
  oxc-parser: ^0.101.0
  preact: ^10.27.2
  react: 19.2.0
  react-dom: 19.2.0
  typescript: ^5.9.3
  unocss: ^66.6.0
  vite: ^7.2.4
  vite-plugin-singlefile: ^2.3.0
  zimmerframe: ^1.1.4
  zod: ^4.1.13
