packages:
  - packages/*
  - examples/*

catalog:
  '@hono/mcp': ^0.1.5
  '@modelcontextprotocol/sdk': ^1.22.0
  'oxc-parser': ^0.98.0
  '@types/node': ^24.10.1
  '@types/react': ^19.2.6
  '@types/react-dom': ^19.2.3
  hono: ^4.10.6
  magic-string: ^0.30.21
  preact: ^10.27.2
  react: ^19.2.0
  react-dom: ^19.2.0
  rolldown: ^1.0.0-beta.51
  typescript: ^5.9.3
  zimmerframe: ^1.1.4
  vite: ^7.2.4
  zod: ^3.25.76
