// This file is auto-generated by chapplin. Do not edit manually.
// To regenerate, run `vite build` or `vite dev`

declare module "chapplin:mcp-server" {
  import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
  /**
   * Create a new MCP server instance with all registered tools, resources, and prompts.
   * Each call creates a fresh instance, which is needed for transports like StreamableHTTPTransport
   * that require a new server per request.
   */
  export function createMcpServer(): McpServer;
  export default createMcpServer;
}

declare module "chapplin:tools" {
  export interface Tools {
  }

  export type ToolName = never;
}

declare module "chapplin:resources" {
  export interface Resources {
  }

  export type ResourceName = never;
}

declare module "chapplin:prompts" {
  export interface Prompts {
  }

  export type PromptName = never;
}
